trigger:
  branches:
    include:
      - main  # Altere "main" para o nome da branch que você deseja acionar a pipeline

jobs:
- job: ExecuteScript
  displayName: 'Execute PM2 script'
  pool:
    vmImage: 'ubuntu-latest'  # Escolha a imagem do agente que corresponda ao seu ambiente de execução
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd /home/meucurso/verticalizado-backend
        pm2 start ecosystem.config.js
