trigger:
  branches:
    include:
      - main  # Altere "main" para o nome da branch que você deseja acionar a pipeline

jobs:
- job: ExecuteScript
  displayName: 'Execute PM2 script'
  pool:
    vmImage: 'ubuntu-latest'  # Escolha a imagem do agente que corresponda ao seu ambiente de execução
  steps:
  - script: 'npm install pm2 -g'
    displayName: 'Install PM2'
  - bash: |
      cd /home/meucurso/start
      pm2 start ecosystem.config.js
    displayName: 'Execute PM2 script'
